### ISSUE TITLE
Make Taskbar an Importable Template

### ISSUE THREAD

**Issue by TheVanadium** [KevinHu101/CV-Tech-Team-Web-App#10]
Change the taskbar from manually inputted into each page to a template imported from a single file.
This can be done through a separate .html file imported through javascript, or a custom tag.

This way we ensure that the taskbars are identical across all the pages. In addition, it makes editing the taskbar easier, as you only need to edit the taskbar file to change the taskbar throughout the whole website.

**Comment by KevinHu101** [comment]
Done!
