### ISSUE TITLE
Specify the Meaning of STL on the Website

### ISSUE THREAD

**Issue by TheVanadium** [KevinHu101/CV-Tech-Team-Web-App#11]
It isn't apparent to me what STL means on the website, so it likely isn't clear to the user either. 

We should possibly look to changing the tab menu appropriately and/or changing the webpage title.

**Comment by KevinHu101** [comment]
STLs stands for student tech leaders, and it is supposed to be only for certain people who have an account for it. My idea is only STLs will know what that page is.
